'use strict';
const el=id=>document.getElementById(id);
let busy=false, connectedBase=null;
const apiBase=()=>{const raw=el('base').value.trim()||location.origin;const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error('API地址必须是无凭据、查询参数或片段的HTTP(S)地址');return u.href.replace(/\/$/,'');};
function clearResult(){el('metrics').replaceChildren();el('flags').replaceChildren();el('raw').textContent='暂无';el('log').textContent='';}
function log(text){el('log').textContent+=new Date().toISOString()+' '+text+'\n';}
async function request(path,method='GET',body,withoutAuth=false){
 const headers={'Accept':'application/json'};if(body!==undefined)headers['Content-Type']='application/json';
 if(!withoutAuth&&el('token').value)headers.Authorization='Bearer '+el('token').value;
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 let r;try{r=await fetch(apiBase()+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal,redirect:'error'});}finally{clearTimeout(timer);}
 const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw Error('API未返回JSON；请检查地址');}
 log(method+' '+path+' → HTTP '+r.status);
 if(!r.ok){const err=Error('HTTP '+r.status+' '+JSON.stringify(data));err.status=r.status;err.data=data;throw err;}
 return data;
}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){el('status').textContent=e.message;el('raw').textContent=JSON.stringify(e.data||{error:e.message},null,2);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function connect(){clearResult();connectedBase=null;el('service').replaceChildren();el('health').textContent='连接中';try{await request('/health');const items=await request('/v1/catalog');if(!Array.isArray(items))throw Error('目录不是服务列表');for(const item of items){if(!['a2a-interaction-trace','a2a-interaction-risk-report'].includes(item.service_id))continue;const opt=document.createElement('option');opt.value=item.service_id;opt.textContent=item.name+' · '+item.price+' credits';el('service').append(opt);}if(!el('service').options.length)throw Error('未发现支持的服务');el('service').value='a2a-interaction-risk-report';el('catalog').textContent=items.filter(x=>x.service_id.startsWith('a2a-interaction-')).map(x=>x.name+': '+x.price+' credits').join(' / ');connectedBase=apiBase();el('health').textContent='真实 API 已连接';el('status').textContent='目录读取成功；以实际报价决定订单金额';}catch(e){el('health').textContent='连接失败';throw e;}}
async function sample(name){const r=await fetch(name+'.json');if(!r.ok)throw Error('示例输入加载失败');el('events').value=JSON.stringify(await r.json(),null,2);}
function render(delivery){const o=delivery.output;if(!o||!Array.isArray(o.risk_flags))throw Error('报告缺少必要字段');el('raw').textContent=JSON.stringify(delivery,null,2);el('status').textContent='分析报告 '+delivery.status+' · '+delivery.trade_id+' · 结算 '+o.credit_settlement;const values=[['Execution Score',o.execution_score,'仅描述本次提交事件'],['Evidence Weight',o.evidence_weight,'来源权重 不是真实性概率'],['任务完成',String(o.completed),'内层任务状态'],['记录交付',String(o.delivered),o.confidence]];for(const [title,value,note] of values){const card=document.createElement('div');card.className='metric';const label=document.createElement('span');label.textContent=title;const b=document.createElement('b');b.textContent=value;const small=document.createElement('span');small.textContent=note;card.append(label,b,small);el('metrics').append(card);}for(const flag of o.risk_flags){const row=document.createElement('div');row.className='flag';const title=document.createElement('strong');title.textContent=flag;const meaning=o.interpretation?.flags?.find(x=>x.flag===flag);const p=document.createElement('p');p.textContent=meaning?meaning.zh+' — '+meaning.en:'API未附逐项解释；保留此风险标记。';row.append(title,p);el('flags').append(row);}}
async function run(){clearResult();el('status').textContent='正在向真实API请求';if(connectedBase!==apiBase())throw Error('API地址已变更，请先重新连接目录');const input=JSON.parse(el('events').value);const budget=Number(el('budget').value);if(!Number.isInteger(budget)||budget<0||budget>100)throw Error('预算须为0至100整数');const buyer_id=el('buyer').value.trim(),service_id=el('service').value;if(!buyer_id||!service_id)throw Error('请填写买家和服务');const quote=await request('/v1/quotes','POST',{buyer_id,service_id,budget});log('报价策略 '+quote.pricing_policy_version+' ask='+quote.ask_price+' floor='+quote.reservation_price);if(quote.pricing_policy_version!=='arena-fixed-v1')throw Error('Runtime尚未使用arena-fixed-v1；停止下单，请部署最终定价');let amount=quote.ask_price;if(el('offer').value!==''){const buyer_offer=Number(el('offer').value);if(!Number.isInteger(buyer_offer)||buyer_offer<1||buyer_offer>100)throw Error('议价须为1至100整数');const decision=await request('/v1/quotes/'+encodeURIComponent(quote.quote_id)+'/negotiate','POST',{buyer_offer});if(!decision.accepted){el('raw').textContent=JSON.stringify({quote,decision},null,2);el('status').textContent='未接受议价；未创建订单'+(decision.counter_price!=null?'，反报价 '+decision.counter_price:'，议价已关闭');return;}amount=decision.final_price;}if(!Number.isInteger(amount)||amount>budget)throw Error('有效价格超出预算，停止下单');const order=await request('/v1/orders','POST',{quote_id:quote.quote_id,buyer_id,service_id,amount,idempotency_key:'dashboard-'+crypto.randomUUID(),input});const path='/v1/orders/'+encodeURIComponent(order.trade_id);log('订单 '+order.trade_id+' 声明金额 '+amount+'，非结算证明');const delivery=await request(path+'/deliver','POST');await request(path);render(delivery);}
el('connect').onclick=()=>action(connect);el('run').onclick=()=>action(run);for(const name of ['success','failure','conflict'])el(name).onclick=()=>action(()=>sample(name));el('unauthorized').onclick=()=>action(async()=>{clearResult();el('status').textContent='测试无凭据访问';try{await request('/v1/quotes','POST',{buyer_id:'unauthorized-probe',service_id:'a2a-interaction-trace',budget:6},true);el('status').textContent='HTTP 200：服务允许无凭据询价，未证明授权保护';}catch(e){el('status').textContent=e.status===401?'HTTP 401：真实API拒绝无凭据请求；未创建订单':e.message;el('raw').textContent=JSON.stringify(e.data||{error:e.message},null,2);}});
action(async()=>{await sample('success');await connect();});

el('quote-only').onclick=()=>action(async()=>{clearResult();if(connectedBase!==apiBase())throw Error('请先连接当前API目录');const budget=Number(el('budget').value);if(!Number.isInteger(budget)||budget<0||budget>100)throw Error('预算须为0至100整数');const q=await request('/v1/quotes','POST',{buyer_id:el('buyer').value.trim(),service_id:el('service').value,budget});el('raw').textContent=JSON.stringify(q,null,2);el('status').textContent='免费报价已返回：报告报价 '+q.ask_price+' credits，底价 '+q.reservation_price+'；未创建订单。';});
